language: node_js

node_js:
  - stable
  - "4.2"
  - "iojs"

sudo: false

before_install:
  - sudo apt-get install lua5.1 luarocks -y
  - sudo luarocks install busted
  - wget http://download.zeromq.org/zeromq-4.1.3.tar.gz
  - tar xzvf zeromq-4.1.3.tar.gz
  - cd zeromq-4.1.3 && ./configure --prefix=$HOME/zeromq && make && make install