language: node_js

node_js:
  - "4.2"

env:
  - LUA='Lua 5.1'

sudo: true

before_install:
  - wget http://download.zeromq.org/zeromq-4.1.3.tar.gz
  - tar xzvf zeromq-4.1.3.tar.gz
  - cd zeromq-4.1.3 && ./configure --without-libsodium --prefix=$HOME/zeromq && make && make install && echo /usr/local/lib > /etc/ld.so.conf.d/local.conf && ldconfig

install:
  - sudo apt-get update -qq
  - sudo luarocks install busted