language: node_js

node_js:
  - "4.2"

env:
  - LUA='Lua 5.1'
  - LUA='Lua 5.2'
  - LUA='Lua 5.3'
  - LUA='LuaJIT 2.0'

sudo: true

before_install:
  - bash .travis_setup.sh
  - sudo apt-get install libzmq3-dev

install:
  - sudo apt-get update -qq
  - sudo luarocks install busted
  - npm install