language: node_js

node_js:
- '4.2'

sudo: false

cache:
  directories:
  - node_modules

before_install:
- bash .travis_setup.sh

install:
- npm install

addons:
  artifacts: true

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: WJskVZr0p3jVH+wDVTugDAkuZfNhXXhaQVdLdxYGRS9XWsRiHpZ+N3ez1vDCgBUxaZFV7EXpx6t56czGSbD/mi+tSxDTb8TPLnZeqSvRxncCM8W5Gy7fQrFg1U+4fNan8vZ+EeURjlfFH/1z+ed7GVPc+Y6vDXtJWxViZC0nxugY8yaoIoFqBmgN4BZyac3YV4Nk1vmlzD9jRy813XhS0JzoilKPwK8CS6PKvX5YKeODZVtPJgB0Ebz+NPWyXjpgiuinMGnUBCTRE21O6q53s0l1MKnf/fW4yzMZnsExSLqFXVx+m+aqUFTpPxaYjzuF+5ra8duPMs+2MHJUfBAzt7jBZXmJNYCe8Uaf/Zw/B1h5O80hvAKp4fRroMfzSUf/xWBMlReFh1+qee5RpbO+u8dNw8/EtGAZws/BTQku6G4j8u1cFqq21vwi/xp6YCtr0OOkE5jbhxHPqzgK+l3/Ru29+LWA2VRQjoXPWDBbKq6iAjehYGfiN9C9ZbKpeaqxd4EIiknFuGK+FZmB/qJFpiL9tYKYbrL7HCiaH9IcZEF1uE/IKme9tcPT3SEmZk891WH7l4jMZoXbt3Nt2xPGR0Jvjbs16i6BH1t8fVFIBgTJ9lyznAV71Zv1+swex1Tsk/coSaNQFuWcb6cmSeI3TdQXKvkqH5oCCCVjLPXD8zU=
  file: ./build/ox.lua
  on:
    tags: true

env:
  global:
  - ARTIFACTS_PATHS=./logs:./build
  - secure: EGx1iBVB5nA0sHGhIYe8igpcgOhxPUGhKuXbTNRs91hdPKVKbfW7RcaerHbxyvpyJedU4zmvOf5vfLtywanYbWTXsjM8nO31gc85n0NrynvcZpLpkK7vysxyr3texjVC3gzCYCHEpzypYrpRX4SsRcby215G8cG7w61v3clcx5P9PVvJu3LhBS7jRsPlD8hSo/SWrTBmeQd0rV+OPwzHNSJAv/0K4qfXFsPeWNBicHIRJkyUQ4Y3uEIfIap4rjmeTt3aFy2uUSzPVJXlmkmBFua+CBnz4AahvkF5IrkjB2U1LIZfPz7lFSv9G+RL07d3H+wr7x7nWPkWKu2lHr9boX6drLO7m/gP494SRJAKfkKfN3R7BMmkk7ZUOUKezpIhQjiFcp+6VzA71Lblr9Z/Z6/Aft7DaWrVT+RTiWTgKflLsMXc01Qz3kWiWw9bbvYNaF5yU/a7tnJ1oX+KF8W828Yt2Fo9TnROzlXEgDlOfuhScjC13m1NGdpOUNIOUQrhZ+Lz28LajCXoCJkqBSGq25AGzf8rMw+Oy98NCt1itch0rbEjbnzZaAK2Rrt/8UD6SVEW/ivk/Aaeo++8xjy+LaL7lR5dv3kgYbqDF+1v2sw/d1XGEAHgww3BeaV7bNkRYcBEa26mm22sgRo96yB5Uy9xCllECQpI9i3+8yjvox8=
  - secure: OeN86FJYpGUfEBWcPz0joh7LEMJKGiVmAZYPZoEqrw67wM66LUs8v5SQzmXrEMcPX1/Wvl/yQsB6HKRMiclgz1X9kK5fDHnm2MAGxOsNFyhIDuKjjCRy/JAlRegmH/BGCftzjTux3WtenfxpbU0na04PIELbysuCLYEjjIbtqqZOi/KOGAnjiRU/BUluLAyespkZKShAdOIVyIsInHU65UWFzIVNpWYNLoMXuzl9AhAI13G+IQC5gSSm/aCJ2M2N0EJYwyhkbimZiPDBvD5MgolY/wapRI4teKR+bITGLeWBKUv/lPftPme/yLP3Hj5RIyXgfGcUzg31zqoLEDInY5pQ7x/8IZaaIv63EGpb4Pd04T+JkKpMgbjajI7/apkSZBsNEDC90M8vjfiizWMXNywzOpRCpeXduv02Z4iyd0Q1KcordrtwN49/0HFIm0gwE8zqLIgVgCaekmr4A03zL+YE4NOmuFlb0Kg0efu1lZ6UO4AyQnH58IWbuzuzsmzpriZbVjJGihw/F0Z1RjwPPN4+TwUEiKpYaqOKqIvJqpgJCunPj+PnnyHTtBrXyLWFEimY4ffEERVun7a72cDqtn+3GVBre0ijTHlr8WakKdUOzNvb3zoEBhRwOuc3SO1yAy7vqTLkmorlf9Bz7iWtRifdZdfvJTaZIDdum/98GKY=
  - secure: HYA+hIzYPjJ8dxKDn6O74fopP+P434TONa73Sfhr6ZoDVWFAFx3i2sixtSPQxoU4EnKR5mkTdDYXyNOZchtBpziAzKEJo7mYJPEW07LPau2IIYhATWRhOuUQ97607vynWVP6WZlLyQcSubBE7+ZvL8l7DRO8ZktVzKouM+DHR7bW06mzNbkiPrLJU6Znu+g2qkHs5T1ea96+8HuVBXH+G8xctEfyEEOiPkLzhF9JcSyOHKB6a0Vt9FdHaBoAtWTb/+LwLdzM3LNg6Tr3sNqaYjecnaidpaisww8FCRDpimdbG9PwNGOl1TwYhEr18/ym4IFS+n7Qg4ehCeJ5O+LGbHn00lMWh8Vler3Vdj46rknyzlR19Ed6m1lyakc0Q8JQRdId3ONAEh/9XVcO1OhwDldS253d756PIOoQcAGfvkBwe5pvMXhWT2O4XR/wqkfKvzhKgJpXMS2ukAyqi1C1KLdbMtQGtc8yXXewwBo9eBJ5OjUt4MUaBunA5ZQH2o67NwgkP0ZI9M9H0/XccliqVfVTBK3dpwCMxv6vCvVRjoCw+UOgqF4vbwKrmixndWFHnn27z9mixRwg9Do46N8n6549afIaBPHbI8NZrHkTCo9xCVesbiWMzoqqCbwviwY6PUo0WU+7/8yS+tsEBo2F2c66p5L4GBfcX+irZ8omILE=
