# Setup environment
language: node_js
node_js: 4.2
sudo: false
cache:
  directories:
    - node_modules  
env:
  global:
  - secure: eU6Qni0UZeJfOD/+lUsaEwVWYKqHjcBDbG0FL+VQ/uJV3Ier10ifQByqf2/ULlc6K8skhyyTxAcmNvTmyiwoVunHMC3JCiK8JkIyFopwx39cuvCZAGaR+6QOXZabYCcsR42v1X53CYQiPd+C5nf39kqwYWLTCh+oOTSYVtrloJ3bkLF0x0vkckaTjZWWcjkFix50MMhHYaYvEbjg6XLS2Gw276GkVW8QFXo4FF7rDnuKjmVGZIxnmKHddHtBKVSbbLVyM8U7O84k1w89Bb49NhApS2WbfssV9dLwzktrAeJQ+jZhat6h75IPijgaoR1l2zDpIT03GGBxgsDzQq3cTOL+WKMQI+PI5vLCKvH8uoPMY2gbCD1YsQcIyC4TrpFruWC1rkO+IxBwthA/hOhDWYkiru9w00Ebk1KX/VzmPGk67YNQfCDHXXt76bmUygLcwITdqQA7UtcWs8P5Oxe3BJ6UPUCRllJ88PoGjbK8fGYH9Jz1FubNPvZG8cSBOyG6D7Rs7SpAPHEMotK9ZgyPBGbzbIpSnV89tCm890+UfLZZ+4/p+cmEcN8b/bZoyn8x0t/tLxaM2MN9BpDa3ozQc2YCs7Ve41eqOlnmFZrrthw8qDxSgmApjr4mtooAku0j+S6Fe4kAfjuumGKAXyZVbvFIJ4yidO+cRzOrjbWli7w=
  - secure: G6B3HnSMNrETAW/uJ1kcstldEQXI2VKnFuUpayM7aIsrLqpa0TbN1KImUIAe3iuBUM0FxzYelaxwbF6ONi6sBAxcrETgUDkbaKVzytbXUNrie2eeiKn5fbPaUqiwjbiPR2oQWeIwaTooKH8mIQ+1L4s2fxN4GrIbusOBa3mfR95bAaF3gDvrPFJA+wH7CTby4PUZ0g6pTnCSoJtyWb13mavANnwOFsB4H1meNvOaRQK5TXTEaFrIZKKkg2grFnTUsHK83v7Qjcl/eC2QgbZ3j0BmdEJmPqfau7L5dXARwj/xVJXz5RcMhwk4izkk+x0Mp8PrG/acBx3zgmgrgWNllrkNBf+KXgcYae1ehLRlTsWDl1nhK6WJGK+XXUH7582+q51e/iB6b3BO0w8hO3OyDaAItdAipVwLU58M5QMyLdPv1U7Cp+upn1jaOStRH48fRJ/AD5AT4iZMLGgDO7y9eyrIupx0xw3t5ctIOtk8OZjkpfBErk2KypYqqRnuygI58OfD0AV7mv9ykTfk2EaQykCInyCkMMXla1bGF2qNXQ6g8cmsGjqMay/jcf6iPrF6x5PWFrsEPzaSBOzvzFkQSBfNRejLYrl4PbThZDBHIlSjpzLC2Mql9lzVKduHhicq4cbgVjZGUAFZhPKFLOdl9HxaWqRDW9mvezRYnYA6f8E=
  - secure: tcI1V/HEhtES4oedepzWP6PdI6UT15TUIHOh6HfJ8R77P+yIXJlE4pRG9HW+ZCmd7q1FO1/2N9GLIBzOWgWwNOE8KHLtw/qiBdX1nDiSXCn5JxTrVc92Sq0YnG2bcW2IkLTCGt1Z4JqUA4MPEC9Qo1bjp9voeFNgC3FdEupVfX9OFcVkRdcx/mIVNL7oVjRa2DeO3cABSQPc4qobD2qKCQy4Q6F12oPCKO1WYKWQQ2D44ZHLEWR2olfvyoGDcczEVYIfFY7bhB6iwaAJjI2y5hL3Tbn+8ck4cNYAz/YUSskda2jfj+rCjyOIPwAaXgRZNseMkqICgluZk5k2aU9Byej/K+gg9wVBkTjfsL8IlJNVIOz2tO4FH+IAWWwpBAia9FEgYd7JgiLkCMeLuv/TlZPQ5F1pMI8Hn0tqaQ72sfAaKJJ62CyYMJ8SW0sOZk+ZzSoNY16wdfIHe+qpaNm/Mu1XIcUEsncBj5l521Fw3grLpQfH0+gQ2AEGw6DLxpxTSFq5lGkjSLJRCf9EKDEg4Tl7Y0bZ79+MjOsj2tUsx3J7QXLmHCNhZAhk5TM6/qENnwPVHkzKayHNuiLfzNAQGnz+dfIuDr6VBmtl8psnNzR8pPYiovT8fZU4d/dLcf67ma3oJxi8JlK0tAW2qfIEbxyXECu7zMWfygSTU/L7+Ew=

# Install misc dependencies
before_install:
  - wget -O - http://www.lua.org/ftp/lua-5.1.5.tar.gz | tar xz
  - cd lua-5.1.5 && make linux local
  - export PATH=$PATH:$PWD/bin
  - cd ..

# Install node dependencies
install: npm install

# Build scripts
script: npm run build

# Upload build artifacts
deploy:
  # Github Release
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: WJskVZr0p3jVH+wDVTugDAkuZfNhXXhaQVdLdxYGRS9XWsRiHpZ+N3ez1vDCgBUxaZFV7EXpx6t56czGSbD/mi+tSxDTb8TPLnZeqSvRxncCM8W5Gy7fQrFg1U+4fNan8vZ+EeURjlfFH/1z+ed7GVPc+Y6vDXtJWxViZC0nxugY8yaoIoFqBmgN4BZyac3YV4Nk1vmlzD9jRy813XhS0JzoilKPwK8CS6PKvX5YKeODZVtPJgB0Ebz+NPWyXjpgiuinMGnUBCTRE21O6q53s0l1MKnf/fW4yzMZnsExSLqFXVx+m+aqUFTpPxaYjzuF+5ra8duPMs+2MHJUfBAzt7jBZXmJNYCe8Uaf/Zw/B1h5O80hvAKp4fRroMfzSUf/xWBMlReFh1+qee5RpbO+u8dNw8/EtGAZws/BTQku6G4j8u1cFqq21vwi/xp6YCtr0OOkE5jbhxHPqzgK+l3/Ru29+LWA2VRQjoXPWDBbKq6iAjehYGfiN9C9ZbKpeaqxd4EIiknFuGK+FZmB/qJFpiL9tYKYbrL7HCiaH9IcZEF1uE/IKme9tcPT3SEmZk891WH7l4jMZoXbt3Nt2xPGR0Jvjbs16i6BH1t8fVFIBgTJ9lyznAV71Zv1+swex1Tsk/coSaNQFuWcb6cmSeI3TdQXKvkqH5oCCCVjLPXD8zU=
    file: "./build/scripts.zip"
    on:
      tags: true

  # Beta Release (master)
  - provider: script
    script: deploy-beta.sh
    on:
      repo: OXGaming/oxscripts
      branch: master

  # Public Release (tagged)
  - provider: script
    script: deploy-release.sh
    on:
      repo: OXGaming/oxscripts
      tags: true

notifications:
  slack:
    on_success: always
    secure: lSNpU7Ws7C9D2EsR9EBw8axb11R8QnDjwEm+b/lXk1MoIr1BbpUMQGL8APgLb2I9/PKvLkASPC4E5yTTGYJnGhGx+QJDCP3GlAvaaSSqjoC/XMATmCLNvrLcKkZ+UmbqPF7anr7Ty7qPW3cGTeN05MS28q3GZ719o/beFGc5E/gPEXyhf5QkHeK0ynzaVhq8JEJMm5dTufjckW0HN9ZPA06L5uSouSsso1FqlicMcL1y0o3eYI+ELMvNbJGiXa9OWdRHnWmjQG1M5MCoAXan5UV2jP5Np9ouytS4GSTF5IOllaPi94KFEamBRzaLns7ck9XGxuusuMP4+HxAKizNs+q14zPo5DDwGOydjPFcWUiqJwV6Af+gnKotts9GaXCu86NpzzgQ7iwRiyBVvC4E99K9o6KyGcpbzQy/zuSXWj392dDS0JMJGIGkxnICycMS9+z/waPBt/V1u6Qx7J2wZ6aWJI7Mf7WouJnceApj+NbVRJo6hxOY4Fq37oT3CDEshp1hwW9HC3lGmROztWoV0QQNxecBcVrqPqKipXEN/0mfwN04Hwk1k6ZcJd+MbAMN5VaecIPYUs+a1nBjfwuqIEJJFsVe+UF0awGvYmru0PkJMyyy0qX2wb45b3csDEMJmGALe+Ddtx9sDnW6KJ1C17Mp/dThIazs+APrdpT9mQg=