language: node_js

node_js:
  - "4.2"

env:
  - LUA='Lua 5.1'

sudo: true

before_install:
  - wget http://download.zeromq.org/zeromq-3.2.4.tar.gz
  - tar -xf zeromq-3.2.4.tar.gz
  - cd zeromq-3.2.4
  - ./configure --prefix=$(readlink -f ..)
  - make && make install
  - export CXXFLAGS="-I $(readlink -f ../include)"
  - export LDFLAGS="-L $(readlink -f ../lib) -Wl,-rpath=$(readlink -f ../lib)"
  - bash .travis_setup.sh

install:
  - sudo apt-get update -qq
  - sudo luarocks install busted
  - npm install