language: node_js

node_js:
  - "4.2"

env:
  - LUA='Lua 5.1'

sudo: true

before_install:
  - bash .travis_setup.sh

install:
  - sudo apt-get update -qq
  - sudo luarocks install busted
  - npm install